apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rger-app
spec:
  project: default
  source:
    repoURL: "https://github.com/KeenGWatanabe/cicdContainer1.git"
    targetRevision: main
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: rger-ns
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true